{{- if .Values.scalerEnabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scaler
spec:
  schedule: {{ .Values.scaler.frequency | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scaler
            image: "{{ .Values.scaler.image }}:{{ .Values.scaler.tag }}"
            env:
            {{- range $key, $value := .Values.scaler.config }}
            - name: {{ $key }}
              value: {{ $value | quote}}
            {{- end }}
          restartPolicy: Never
{{- end }}